#Dashing2 Symmetric pairwise Output
#Dashing2Options: Dashing2Options;k:32;parsebyfile;trimchr;sketchsize:1024;sketchtype:onepermsetsketch;Fastx;canon
#Sources	/home/smao10/zzz/triesketch/data/eukarya/GRCm39_genomic.fa	/home/smao10/zzz/triesketch/data/eukarya/Mmul_10_genomic.fa	/home/smao10/zzz/triesketch/data/eukarya/NHGRI_mPanTro3_genomic.fa	/home/smao10/zzz/triesketch/data/eukarya/TAIR10_genomic.fa
/home/smao10/zzz/triesketch/data/eukarya/GRCm39_genomic.fa	-	0.0009765625	0	0
/home/smao10/zzz/triesketch/data/eukarya/Mmul_10_genomic.fa	-	-	0.083984375	0
/home/smao10/zzz/triesketch/data/eukarya/NHGRI_mPanTro3_genomic.fa	-	-	-	0
/home/smao10/zzz/triesketch/data/eukarya/TAIR10_genomic.fa	-	-	-	-
